### ISSUE TITLE
Question about 'dataLenPerFile'

### ISSUE THREAD

**Issue by 2gunsu** [zb12138/OctAttention#1]
Thank you so much for sharing a great project.

I have converted 23201 ```*.bin``` scan files from SemanticKITTI to ```*.mat``` files using ```dataPrepare.py```,
and calculated **'dataLenPerFile'** using ```DataFolder.calcdataLenPerFile()``` method as you mentioned.

But from the code below your **'dataLenPerFile'** seems to be 17456051, but in my case 121484 is obtained. 
I wonder if this is a value that can vary depending on the environment.
https://github.com/zb12138/OctAttention/blob/aed8279bc82c7d6c76f3cf9eb1d383fd821fc0df/octAttention.py#L143

Thank You.

**Comment by zb12138** [comment]
Thank you for the comment. I checked our data and found that it contained 178 MAT files, and one MAT file contains 128 point clouds. (So only 22,528 point clouds are used, not all the data is used). Since 121484*128 ~ 17456051, I think your result is correct.

**Comment by 2gunsu** [comment]
Thank you so much for the quick and kind reply. 
Have a nice day!
