### ISSUE TITLE
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by wjz51** [zb12138/OctAttention#11]
I am running dataPrepare.py
This code：lib = cdll.LoadLibrary(os.path.dirname(os.path.abspath(__file__))+'/Octree_python_lib.so') # class level loading lib
Display errors at runtime：OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
So I want to ask what your operating system is...?

**Comment by zb12138** [comment]
Only works in Linux.
