### ISSUE TITLE
Question about figure 5

### ISSUE THREAD

**Issue by Py-debug** [zb12138/OctAttention#12]
Hi, I'm suprised about your paper, and i want to try the visualization. could you please give me the code about the figure 5? thanks a lot.

**Comment by zb12138** [comment]
Thanks for your attention. [Here's](https://portland-my.sharepoint.com/:f:/g/personal/chunyanfu2-c_my_cityu_edu_hk/Et8Bc8fOJldAt1txrP706FEBxhYlfw-ua0RcxbYOlpUDKQ?e=YfTouz) the raw data and code. Since it's been so long, I can't guarantee they'll work well. But I hope it helps.
