### ISSUE TITLE
Prepare data code does not work

### ISSUE THREAD

**Issue by husnejahan** [zb12138/OctAttention#13]
I have used the following command:

python dataPrepare.py

My directories are as follows:

  oriDir = '/8iVFBv2/longdress/Ply/*.ply'
  outDir = 'Data/Obj/train/'

**Comment by zb12138** [comment]
Please make sure there are plys in oriDir.

**Comment by husnejahan** [comment]
Hi,
yes it has all ply files in it.

I figured out in data.py file 

 if offset == 'min':

instead of

if offset is 'min':

Thank you.

**Comment by husnejahan** [comment]
DataSturct = GenKparentSeq(Octree, 4) is there any reason you have selected k=4 here?

**Comment by zb12138** [comment]
Thank you. The problem about ' == ' is caused by the Python version. 

The related experiment about K is in the octsqueeze.
