### ISSUE TITLE
A question about tmc

### ISSUE THREAD

**Issue by jiatianluo** [zb12138/OctAttention#14]
I am trying to run your program on the Jetson ORIN NX, which has Ubuntu 20.04 installed. However, due to its ARM-based processor, while your program seems to be compiled for the x86_64 architecture, I encountered an error when running `python3 testTMC.py`: ./file/tmc13v14_r: Exec format error. What should I do to correctly run your program?

**Comment by zb12138** [comment]
You can recompile it via https://github.com/MPEGGroup/mpeg-pcc-tmc13.

**Comment by jiatianluo** [comment]
I have read it before,but I still don't understand the steps to recompile,Can you provide more specific set of steps  about it?Thank you!

**Comment by jiatianluo** [comment]
I want to cross-compile tmc13v14_r on an x86 platform for use on an ARM target platform.How should I proceed?
