### ISSUE TITLE
Why the decoding time is so long? Do I need to set any parameters？

### ISSUE THREAD

**Issue by SekaiNoOwari77** [zb12138/OctAttention#15]

**Comment by zb12138** [comment]
No. This is a disadvantage of autoregressive models. The relevant improvements can be referred to the paper [EHEM](https://openaccess.thecvf.com/content/CVPR2023/html/Song_Efficient_Hierarchical_Entropy_Model_for_Learned_Point_Cloud_Compression_CVPR_2023_paper.html)
