### ISSUE TITLE
Evaluating at different bitrates

### ISSUE THREAD

**Issue by anustupc** [zb12138/OctAttention#16]
Hello,
Thanks for the great work and making the code available. I would like to understand the model performance at different bitrates. 
Could you help me with the following 2 questions - 
1) The paper mentions that the octree is truncated at 8-12 levels during testing. How do I set that value in the encoder.py and decoder.py files?
2) To compute the amount of compression, can I use the size of the rec.ply file or the size of the 2851.bin file? The bin file seems to have a very small size.

**Comment by zb12138** [comment]
Hi,
For question 1, you can set `qlevel` here:
https://github.com/zb12138/OctAttention/blob/436376cd95dea17096a0463116eb718af8d40dff/encoder.py#L31
For question 2, I don't know what 'amount of compression' means?

**Comment by anustupc** [comment]
Thanks for your prompt reply. 
For question 1, can you explain what is the difference between the encoder.py file between the obj and the lidar branch? The one in the obj branch does not have the qlevel variable but the one in the lidar branch does. What would be the best way to set the value of qlevel in the obj branch?

For question 2, I wanted to understand how to get the bpp value for different values of qlevel.

**Comment by zb12138** [comment]
Okay. For obj branch, we perform lossless compression. We just set qs=1 and the qlevel is automatically determined `qlevel = ceil(log2(max_geo-min_geo))`. For question 2,  `bpp=binstream_size/point number before quantization`, where `binstream_size` is the size (in bits) of the model output ('*.bin' file), and `point number before quantization` is fixed for different qlevels.

**Comment by anustupc** [comment]
Thanks for your reply. 
On question 1, is it fair to say that for the obj branch, in the encoder.py file, if we replace qs with qlevel and set qs as 2/(2**qlevel-1) (Similar to the lidar branch) and vary the values of qlevel from 8 to 12, we would then be getting the model performance at different bitrates? We can then create a curve with qs=1 for lossless and the different values of qlevel can be the lossy encoding.
I am clear on question 2 and thanks for that.

**Comment by zb12138** [comment]
Yes, it is. But frankly, OctAttention is primarily aimed at lossless geometry compression and does not represent the most advanced performance of lossy compression on the dense obj point clouds, as no transformations are introduced. The related model for lossy compression can be found in PCGCv2.

**Comment by anustupc** [comment]
Thanks for your reply. 

In order to run both the lossless and lossy versions, I made some quick changes to the code and ran it on the 2851.ply as follows: 
```
for qs in [1]:
            ptNamePrefix = ptName
            matFile,DQpt,refPt = dataPrepare(oriFile,saveMatDir='./Data/testPly',qs=qs,ptNamePrefix='',rotation=False)
            # please set `rotation=True` in the `dataPrepare` function when processing MVUB data
            compr_mode="lossless"
            main(matFile,model,compr_mode,actualcode=True,printl =printl) # actualcode=False: bin file will not be generated
                       
for qlevel in [8,9,10,12]:
            ptNamePrefix = ptName
            matFile,DQpt,refPt = dataPrepare(oriFile,saveMatDir='./Data/testPly',qs=2/(2**qlevel-1),ptNamePrefix='',rotation=False)
            # please set `rotation=True` in the `dataPrepare` function when processing MVUB data
            compr_mode="lossy_"+str(qlevel)
            main(matFile,model,compr_mode,actualcode=True,printl =printl) # actualcode=False: bin file will not be generated
```
When I look at the bin file, I see that for lossless (qs=1), the size is 3KB. However for the lossy compression with qlevel set to 8,9, 10 and 12, the size of the bin files are 62KB, 66KB, 69KB and 74 KB. 
The size of the files seem much larger. Is this expected or am I making some errors?

Thanks once again for helping me with this.

**Comment by zb12138** [comment]
In this case, 2851.ply is a 7-bits pointcloud. You can try loot_vox10 or set qlevel 4-7.

**Comment by anustupc** [comment]
Thanks for the suggestion. I tried that as well. 
This is for 2851.ply
For the lossless one, with q = 1, the bin file has a size of 3KB. 
For the lossy one, with qlevel = [4, 7], the bin file has sizes of 25KB and 52 KB respectively, which I feel is not expected. 

Do you have any insights into what might be happening?

**Comment by zb12138** [comment]
Can you try data in 8iVFB? because 2851.ply may be too small for this model.

**Comment by anustupc** [comment]
I tried it on the Longdress_vox10_1300.ply and see similar trends.
With qs=1, the bin file has a size of 70KB.
With qlevel=[4, 7, 8], the bin files have a size of 1279KB, 2610 KB and 3049KB respectively.

Is there something wrong with how qs is being set with respect to qlevel?

**Comment by zb12138** [comment]
> Thanks for your reply.
> 
> In order to run both the lossless and lossy versions, I made some quick changes to the code and ran it on the 2851.ply as follows:
> 
> ```
> for qs in [1]:
>             ptNamePrefix = ptName
>             matFile,DQpt,refPt = dataPrepare(oriFile,saveMatDir='./Data/testPly',qs=qs,ptNamePrefix='',rotation=False)
>             # please set `rotation=True` in the `dataPrepare` function when processing MVUB data
>             compr_mode="lossless"
>             main(matFile,model,compr_mode,actualcode=True,printl =printl) # actualcode=False: bin file will not be generated
>                        
> for qlevel in [8,9,10,12]:
>             ptNamePrefix = ptName
>             matFile,DQpt,refPt = dataPrepare(oriFile,saveMatDir='./Data/testPly',qs=2/(2**qlevel-1),ptNamePrefix='',rotation=False)
>             # please set `rotation=True` in the `dataPrepare` function when processing MVUB data
>             compr_mode="lossy_"+str(qlevel)
>             main(matFile,model,compr_mode,actualcode=True,printl =printl) # actualcode=False: bin file will not be generated
> ```
> 
> When I look at the bin file, I see that for lossless (qs=1), the size is 3KB. However for the lossy compression with qlevel set to 8,9, 10 and 12, the size of the bin files are 62KB, 66KB, 69KB and 74 KB. The size of the files seem much larger. Is this expected or am I making some errors?
> 
> Thanks once again for helping me with this.

I think you shold set `qlevel` and `qs=None`
https://github.com/zb12138/OctAttention/blob/505ceb855d4d231e5fcb8030354167cc75937d80/Preparedata/data.py#L37C12-L37C13

**Comment by anustupc** [comment]
Thanks for the suggestion. Now, I am able to see trends as expected in the size of the bin file.
