### ISSUE TITLE
Trouble in understanding the occupancy code -1

### ISSUE THREAD

**Issue by Psy-UESTC** [zb12138/OctAttention#19]
Hi, I am confused about the operation in the dataset.py DataFolder __getitem__

data[:,:,0] = data[:,:,0] - 1

Looking forward to your reply!

**Comment by zb12138** [comment]
We have added the comment.

**Comment by Psy-UESTC** [comment]
May I ask what is the purpose of the shifting operation? I have cheked the occupancy of the example ply file. It is true that the occupancy code is ranged from 1 to 255.

**Comment by Psy-UESTC** [comment]
Could you please tell me where I can change the Octree's level which generated in dataPrepare.py. I have noticed that you had trained your model with the max Octree depth of 12 in your paper, while the Octree I generated only has 7 depth.
