### ISSUE TITLE
Question about trained weight on SemanticKITTI

### ISSUE THREAD

**Issue by JAS0NN** [zb12138/OctAttention#4]
Thanks for sharing the great work!

I found that there is a trained weight located in the folder **modelsave/obj**, and it was trained on object point clouds.

Is it convenient for you if you upload the **.pth** files trained on SemanticKITTI? Thanks!

**Comment by zb12138** [comment]
Thanks for your interest. You can find the checkpoint if you select the lidar branch, or you can find it here https://github.com/zb12138/OctAttention/tree/lidar/modelsave/lidar

**Comment by JAS0NN** [comment]
Thank you for the prompt reply.
