### ISSUE TITLE
Question about TMC13

### ISSUE THREAD

**Issue by JAS0NN** [zb12138/OctAttention#5]
Hi, 
I have another question about the file `testTMC.py` for lidar point clouds.
Before the compression, the coordinates of lidar point clouds are shifted by mean value and normalized by max value.

I am curios why the mean value and max value are not stored and counted as a part of  bit-stream.

**Comment by zb12138** [comment]
Yes, they should be coded directly, but this code omitted them. In fact, they account for very few bits.

**Comment by JAS0NN** [comment]
Thank you for the reply!
