### ISSUE TITLE
question about tmc3_v14

### ISSUE THREAD

**Issue by tuning12** [zb12138/OctAttention#6]
Firstly thank you for your great work! I have a question aboud using tmc3.
'/bin/sh: 1: ./tmc3_v14: Permission denied' has shown while test the g-pcc. Is there any solutions?

**Comment by zb12138** [comment]
please run ```chmod +x file/pc_error file/tmc13v14``` in bash, and try again.

**Comment by tuning12** [comment]
Thank you for your patient reply. My question has been solved.
