### ISSUE TITLE
Source code of OctreeCpp 

### ISSUE THREAD

**Issue by HDjpf** [zb12138/OctAttention#7]
Thanks for opening of your work, we hope to develop new research on the work, could get the code of octreecpp?

**Comment by zb12138** [comment]
Sorry for the late reply. Because of the copyright of AVS, we cannot share the source code of C++. But you can use the Python version as a reference.


in Octree.py
comment
```
# from OctreeCPP.Octreewarpperimport GenOctree
```
and add 
```
def GenOctree(points,Lmax=None):
    Codes=[]
    mcode = Morton(points)
    if Lmax is None:
        Lmax = np.ceil(mcode.shape[1]/3).astype(int)   
    pointNum = mcode.shape[0]

    mcode2 = np.zeros((pointNum,Lmax))                    
    for n in range(Lmax):
        mcode2[:,n:n+1] = bin2decAry(mcode[:,n*3:n*3+3])   

    pointID = list(range(0,pointNum))
    nodeid = 0
    proot = CNode(childPoint=[np.array(pointID)])   
    Octree = [COctree() for _ in range(Lmax+1)]    
    Octree[0].node = [proot]
    for L in range(1,Lmax+1):            
        Octree[L].level = L
        for node in Octree[L-1].node:      
            for octant,PId in enumerate(node.childPoint):   
                if len(PId)==0:
                    continue
                nodeid+=1
                Node = CNode(nodeid=nodeid,parent=node.nodeid)   
                idn = mcode2[PId,L-1]   
                for i in range(8):
                    Node.childPoint[i] = PId[idn==i]   
                occupancyCode  = np.in1d(np.array(range(7,-1,-1)),idn).astype(int)   
                Node.oct = int(bin2decAry(occupancyCode))   
                Node.octant = octant+1
                Codes.append(Node.oct)
                Octree[L].node.append(Node)
    del Octree[0]
    return Codes,Octree,Lmax
```

**Comment by HDjpf** [comment]
Thank you very much for your reply, I will try the code.

**Comment by zlH518** [comment]
Can I ask what the ”PID“ variable is in line “Node.childPoint[i] = PId[idn==i]  ” and line "if len(PId)==0:"of the code?Is it the previous ”pointID“ variable?It seems like it's not.

**Comment by zb12138** [comment]
Sorry for the typo. I have updated it. More information about octree can be found here https://github.com/zb12138/PointCloud-Octree-Compression-

**Comment by zlH518** [comment]
thank you very much

**Comment by zlH518** [comment]
I noticed that the octree result created by maltab you provided is different from the python file. Can I ask what the reason is?

**Comment by zb12138** [comment]
They just use different octant index conventions.

**Comment by BK-Snowball** [comment]
感谢您优秀的开源工作！想请教您一个问题。我想在一台miniPC（ARM64架构）上做新的研究工作，但Octree_python_lib.so是x86-64 架构，网上也没有Octree_python_lib的源码，请问这样的问题要怎样解决？

**Comment by zb12138** [comment]
Please refer to https://github.com/zb12138/OctAttention/issues/7#issuecomment-1646613775

**Comment by BK-Snowball** [comment]
> Please refer to [#7 (comment)](https://github.com/zb12138/OctAttention/issues/7#issuecomment-1646613775)

感谢您的回复
