### ISSUE TITLE
Nvidia GeForce RTX 3090 - 1 Year Training

### ISSUE THREAD

**Issue by bugerry87** [zb12138/OctAttention#8]
Hi,
you claim that it took you 2 days to train Kitti for 8 epochs on a Titan XP.
Then why it will take me 1 Year on a GeForce RTX 3090 while its utilization is almost 100%.
Is this the actual implementation run in your paper?

**Comment by zb12138** [comment]
Hi, 
thank you for your interest, are you sure it took 1 year in training? Usually it takes 2 days with one suitable GPU. If your loss is steadily decreasing and converging, you can kill the training in due course.
