### ISSUE TITLE
Question about TMC13

### ISSUE THREAD

**Issue by wang15802** [zb12138/OctAttention#9]
First of all, thank you for sharing the project.Why is there such a significant difference in the time for encoding and decoding compared to the results in your paper?

~/code/OctAttention$ python testTMC.py
****TMC V14****
2023-11-07:15:47:02
dataset/MPEG 8iVFBv2/soldier/soldier/Ply/soldier_vox10_0536.ply
__________________________________________________ encode __________________________________________________
MPEG PCC tmc3 version unconfirmed-release-14.0
+ Effective configuration parameters
    mode                  : 0
    firstFrameNum         : 0
    frameCount            : 1
    reconstructedDataPath : ""
    uncompressedDataPath  : "./temp/tmc/p.ply"
    compressedStreamPath  : "./temp/tmc/tmc.bin"
    postRecolorPath       : ""
    preInvScalePath       : ""
    convertPlyColourspace : 1
    outputBinaryPly       : 1
    outputUnitLength      : 1
    outputScaling         : 1 (External)
    outputPrecisionBits   : -1
    srcUnitLength             : 1
    srcUnit                   : 0 (Dimensionless)
    inputScale                : 1
    codingScale               : 1
    sequenceScale             : 1
    positionQuantizationScale : 1
    externalScale             : 1
    sortInputByAzimuth               : 0
    geometry_axis_order              : 1 (xyz)
    autoSeqBbox                      : 1
    seqOrigin                        : 0, 0, 0
    seqSizeWhd                       : 0, 0, 0
    mergeDuplicatedPoints            : 1
    partitionMethod                  : 4 (UniformSquare)
    partitionOctreeDepth             : 1
    sliceMaxPoints                   : 1100000
    sliceMinPoints                   : 550000
    tileSize                         : 0
    cabac_bypass_stream_enabled_flag : 0
    entropyContinuationEnabled       : 0
    disableAttributeCoding           : 1
    enforceLevelLimits               : 1
    geomTreeType                       : 0
    qtbtEnabled                        : 1
    maxNumQtBtBeforeOt                 : 4
    minQtbtSizeLog2                    : 0
    numOctreeEntropyStreams            : 0
    bitwiseOccupancyCoding             : 1
    neighbourAvailBoundaryLog2         : 7
    inferredDirectCodingMode           : 0
    jointTwoPointIdcm                  : 1
    adjacentChildContextualization     : 1
    intra_pred_max_node_size_log2      : 6
    planarEnabled                      : 1
    planarModeThreshold0               : 77
    planarModeThreshold1               : 99
    planarModeThreshold2               : 113
    planarModeIdcmUse                  : -1
    trisoupNodeSizeLog2                : 
    trisoup_sampling_value             : 0
    positionQuantisationEnabled        : 0
    positionQuantisationMethod         : 0 (Uniform)
    positionQpMultiplierLog2           : 0
    positionBaseQp                     : 4
    positionIdcmQp                     : 0
    positionSliceQpOffset              : 0
    positionQuantisationOctreeSizeLog2 : -1
    positionQuantisationOctreeDepth    : -1
    positionBaseQpFreqLog2             : 8
    positionSliceQpFreqLog2            : -8
    angularEnabled                     : 0
    lidarHeadPosition                  : 0, 0, 0
    numLasers                          : 0
    lasersTheta                        : 
    lasersZ                            : 
    lasersNumPhiPerTurn                : 
    planarBufferDisabled               : 0
    predGeomAzimuthQuantization        : 1
    positionAzimuthScaleLog2           : 5
    positionAzimuthSpeed               : 362
    positionRadiusInvScaleLog2         : 0
    predGeomSort                       : 1 (Morton)
    predGeomAzimuthSortPrecision       : 0
    predGeomTreePtsMax                 : 1100000
    pointCountMetadata                 : 0
    recolourSearchRange                             : 1
    recolourNumNeighboursFwd                        : 8
    recolourNumNeighboursBwd                        : 1
    recolourUseDistWeightedAvgFwd                   : 1
    recolourUseDistWeightedAvgBwd                   : 1
    recolourSkipAvgIfIdenticalSourcePointPresentFwd : 1
    recolourSkipAvgIfIdenticalSourcePointPresentBwd : 0
    recolourDistOffsetFwd                           : 4
    recolourDistOffsetBwd                           : 4
    recolourMaxGeometryDist2Fwd                     : 1000
    recolourMaxGeometryDist2Bwd                     : 1000
    recolourMaxAttributeDist2Fwd                    : 1000
    recolourMaxAttributeDist2Bwd                    : 1000

Slice number: 1
positions bitstream size 136014 B (1.0267 bpp)
positions processing time (user): 2.349 s
Total frame size 136049 B
Total bitstream size 136049 B
Processing time (wall): 4.252 s
Processing time (user): 3.595 s
ptNum:  1059810
binsize(b):  1088392
tmc bpip:  1.0269689850067465
__________________________________________________ decode __________________________________________________
MPEG PCC tmc3 version unconfirmed-release-14.0
+ Effective configuration parameters
    mode                  : 1
    firstFrameNum         : 0
    frameCount            : 1
    reconstructedDataPath : "./temp/tmc/recPt.ply"
    uncompressedDataPath  : ""
    compressedStreamPath  : "./temp/tmc/tmc.bin"
    postRecolorPath       : ""
    preInvScalePath       : ""
    convertPlyColourspace : 1
    outputBinaryPly       : 1
    outputUnitLength      : 1
    outputScaling         : 1 (External)
    outputPrecisionBits   : -1
    skipOctreeLayers : 0
    decodeMaxPoints  : 0

positions bitstream size 136014 B
positions processing time (user): 0.889 s

Total bitstream size 136049 B
Processing time (wall): 1.051 s
Processing time (user): 0.956 s
__________________________________________________ pc_error __________________________________________________
PCC quality measurement software, version 0.13.5

infile1:        temp/data/pt0pcRefer.ply
infile2:        temp/data/pt0pc.ply
normal1:        
singlePass:     0
hausdorff:      0
color:          0
lidar:          0
resolution:     1023
dropDuplicates: 2
neighborsProc:  1
averageNormals: 1
mseSpace:       1
nbThreads:      1

Verifying if the data is loaded correctly.. The last point is: 261 992 256
Reading file 1 done.
Verifying if the data is loaded correctly.. The last point is: 363 775 345
Reading file 2 done.
Imported intrinsic resoluiton: 1023
Peak distance for PSNR: 1023
Point cloud sizes for org version, dec version, and the scaling ratio: 1059810, 1059810, 1
Normals prepared.

1. Use infile1 (A) as reference, loop over A, use normals on B. (A->B).
   mse1      (p2point): 0
   mse1,PSNR (p2point): inf
2. Use infile2 (B) as reference, loop over B, use normals on A. (B->A).
   mse2      (p2point): 0
   mse2,PSNR (p2point): inf
3. Final (symmetric).
   mseF      (p2point): 0
   mseF,PSNR (p2point): inf
Job done! 1.731 seconds elapsed (excluding the time to load the point clouds).

**Comment by zb12138** [comment]
Hi, 
Thanks for noticing the issue. We found that [tmc3 ](https://github.com/MPEGGroup/mpeg-pcc-tmc13/releases/tag/release-v14.0) will generate debug version on Linux with its default settings, and we have updated it to release version (via cmake... -DCMAKE_BUILD_TYPE=Release).

**Comment by wang15802** [comment]
It works now,thank you.
